### ISSUE TITLE
500 Error When Healthy

### ISSUE THREAD

**Issue by rodnaph** [thecodingmachine/gotenberg#172]
## Expected Behavior
When an internal condition means Gotenberg cannot operate, the healthcheck should fail.

## Current Behavior
When an internal condition appears to be failing, the healthcheck returns healthy.

## Possible Solution
When an internal condition is failing, the healthcheck should also fail.

## Steps to Reproduce (for bugs)
I'm afraid I do not know how to cause a reproduction for this issue.

## Logs (LOG_LEVEL="DEBUG")
```
{
  "level": "error",
  "msg": "Get http://localhost:9222/json/version: dial tcp 127.0.0.1:9222: connect: connection refused",
  "op": "xhttp.htmlHandler: xhttp.convertSync: printer.chromePrinter.Print",
  "time": "2020-02-27T11:16:27Z",
  "trace": "9vALcycdMza3LSm5YGhQSd6CNwXosT56"
}
```

## Context
As mentioned above I'm afraid I don't have a reproduction for how Gotenberg gets into this state, but it appears that something has gone wrong internally which then causes all subsequent requests to fail with a 500 error. But, the healthcheck continues to return ok so our service is not alerted on or restarted.

Any tips or hints greatly appreciated.

## Your Environment
We're running Gotenberg 6.1.2 in AWS ECS.

**Comment by gulien** [comment]
Hello @rodnaph 

It looks like Google Chrome crashed or became unhealthy.
For now you may restart the Gotenberg instance and it should work again.

I should update the ping endpoint in order to detect such cases 👍

**Comment by rodnaph** [comment]
Yes, I thought it was probably that, thanks again!

**Comment by YpNo** [comment]
Hi, 
Any news about this issue ? When will the 7.0.0 version be available ?

Regards.

**Comment by sebastian-schlecht** [comment]
Any updates on this? We are also seeing this crash in production.

**Comment by gulien** [comment]
Hey guys,

I'm currently *uber-busy* at work so I did not work that much on the new version.

As mentioned, this version will provide a better healthcheck. I also plan to implement a sort of "kill it after X seconds if not active" mechanism for Google Chrome. It should mitigate this issue.

Meanwhile, I'll gladly accept a PR to fix this issue in the current version.

Some hints:

- the health check method is located here https://github.com/thecodingmachine/gotenberg/blob/6.3.0/internal/app/xhttp/handler.go#L68
- Google Chrome viability function is located here https://github.com/thecodingmachine/gotenberg/blob/6.3.0/internal/pkg/chrome/chrome.go#L131. You could make this function public instead of private.
- If Google Chrome is enabled (https://github.com/thecodingmachine/gotenberg/blob/6.3.0/internal/pkg/conf/conf.go#L254), do the viability test. The `Context` from the handler contains the `Config` (https://github.com/thecodingmachine/gotenberg/blob/6.3.0/internal/app/xhttp/pkg/context/context.go#L21), but right now it is not exposed.
