### ISSUE TITLE
Add option to enable CORS

### ISSUE THREAD

**Issue by phlppnhllngr** [thecodingmachine/gotenberg#62]
Calling the API from a webpage is currently not possible, if the webpage is hosted on a different domain than gotenberg. The "Access-Control-Allow-Origin" is missing, thus a browser won't let you make the request.
Please consider adding an option to whitelist certain user defined origins.
For example (Docker):
docker run -e ALLOW_ORIGINS='http://some-domain.com,https://another.domain.com:8080'

**Comment by gulien** [comment]
Hello @phlppnhllngr! IMO Gotenberg should be called behind a proxy. Not sure if it is in the scope of Gotenberg ^^

**Comment by mbohovic** [comment]
this didn't help me, I have gotenberg on localhost:9055 and I call it on localhost:6006
I have a CORS error, please how can I solve it?
I installed Gotenberg using docker compose

version: "3"
services: 
  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "127.0.0.1:9055:3000"

Please help, thanks

**Comment by phayes** [comment]
I'd like to ask that this be revisited. 

As part of my work on the rust gotenberg client (https://github.com/phayes/gotenberg_pdf), I'm enabling web-assembly support. I believe it should be working just fine, except that I'm getting errors from firefox due to CORS headers not being emitted by the gotenberg API. 

I understand that it's recommended to run gotenberg behind a reverse proxy, but it would still be useful to be able to set CORS headers on gotenberg directly. 

I'd be happy to open a pull request if this is something you think could be supported.

**Comment by yumauri** [comment]
@phayes Wow, that’s bold—WebAssembly support, I mean!
I am the author of JS client library and still planning to add browser support as well :)

Note, though, that CORS headers are not the only thing you will need to add. You will also need to handle OPTIONS requests, HTTPS support (you’re not using plain HTTP, are you?) with the ability to define an SSL certificate, and possibly HTTP/2 or HTTP/3 support. There is a significant amount of work involved if you want to expose Gotenberg to the internet — it would need to function almost like a fully-fledged HTTP server.

Personally, I don’t think this is necessary when you can simply add a reverse proxy, which already supports everything you need.

**Comment by gulien** [comment]
Hey @phayes @yumauri,

I agree with @yumauri, I think the best option is to put Gotenberg behind a reverse-proxy if you want to expose it to the external world (although I do not recommend this for security reasons).
