### ISSUE TITLE
Gotenberg vs WKHTML2PDF

### ISSUE THREAD

**Issue by Grafikart** [thecodingmachine/gotenberg#64]
It would be interesting to highlight the differences between gotenberg and wkhtml2pdf for converting PDF (aside from the obvious things like "it's a server whereas wkhtml2pdf is a binary) in the README.md. 

I am curious to know if you encountered some limitation with wkhtml2pdf that started the creation of gotenberg.

**Comment by gulien** [comment]
Hello @Grafikart 

- mostly because Google Chrome headless is more up-to-date with the latest HTLM/CSS/JS features. Overall, it performs better PDF rendering.
- we needed a tool for converting Office documents to PDF, a feature which does not exist with wkhtml2pdf.
- we needed a tool which can be easily deployed to a docker-compose file, a Kubernetes cluster, an AWS fargate service etc.

**Comment by Grafikart** [comment]
Thanks
