### ISSUE TITLE
Header and footer display very small text

### ISSUE THREAD

**Issue by shoe-diamente** [thecodingmachine/gotenberg#70]
## Expected Behavior

With an header defined as:

```
<html>
    <head>
    </head>
    <body>
        <span>Ok</span>
    </body>
</html>
```

Header and footer should display text with the same size as the body.

## Current Behavior

The size of the text is much smaller:

![Screen Shot 2019-05-06 at 17 25 27](https://user-images.githubusercontent.com/40760781/57235899-3ca39d80-7024-11e9-9552-ad11edebd245.png)

## Possible Solution

I think I remember this was a common problem with wkhtmltopdf or some other engine, but I can't seem to find the reference.

## Your Environment

* Version used: thecodingmachine/gotenberg:5 (Docker)

**Comment by gulien** [comment]
Hello,

A solution would be using a style like the following in the `head`:

```html
<style>
   body {
       font-size: 8rem;
       margin: 4rem auto;
   }
</style>
```

See https://thecodingmachine.github.io/gotenberg/#html.header_and_footer.

**Comment by aa-ndrej** [comment]
For anyone still landing here, because this is still relevant as of today:

I found that the root cause of the tiny text in the header and footer is that Chromium does not set a `font-size` on the `html` tag (it appears to default to `1px`). As a result, units like `rem` do not behave the same way as they do in the main content section, and you either need to use arbitrarily large values or switch to `px` units.

Simply include the following in your HTML, and everything works as in the main content part of the PDF:
```html
<style>
  html {
    font-size: 16px;
  }
</style>
```
